baseURL = 'https://binhscoco7565.github.io/'
languageCode = 'en-us'
title = "Binhscoco's blog"
theme="smol"

# Parameters
[params]
    subtitle = "random stuff i made"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/binhscoco7565"
        weight = 1 
